<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ceataec.ExampleService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.2.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ceataec.ExampleService.Domain\Ceataec.ExampleService.Domain.csproj" />
    <ProjectReference Include="..\Ceataec.ExampleService.Infrastructure\Ceataec.ExampleService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
